name: Rotate root certs
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 10 1 *"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            software/certifier/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          set -xeu
          export GOOGLE_APPLICATION_CREDENTIALS="$(pwd)/google_creds.json"
          cat > $GOOGLE_APPLICATION_CREDENTIALS << 'PRINCELY_EXCITED'
          ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          PRINCELY_EXCITED
          cargo run --manifest-path software/certifier/Cargo.toml --bin certifier-rotate
        env:
          CERTIPASTA_ROTATE_CONFIG: ${{ vars.CERTIPASTA_ROTATE_CONFIG }}
