name: Rotate root certs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 10 1 *'
jobs:
  rotate-root-certs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            rust/certifier/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo run --manifest-path rust/certifier/Cargo.toml --bin certipasta-rotate
      - uses: actions/upload-artifact@v4
        with:
          name: root_certs
          path: artifact
          if-no-files-found: error
